---
- import_tasks: include-vars.yaml

- import_tasks: load.yaml

- import_tasks: apps.yaml

- import_tasks: dependences.yaml

- import_tasks: files.yaml

- import_tasks: host.yaml

- import_tasks: pip.yaml

- import_tasks: install.yaml
  tags:
    - web
    - pm2
    - install
    - pm2-install

- import_tasks: configure.yaml
  tags:
    - web
    - pm2
    - manage
    - pm2-manage

- import_tasks: environment.yaml

- import_tasks: post_install.yaml

- import_tasks: service.yaml
  tags:
    - web
    - pm2
    - service
    - pm2-service
