# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: '3.6'
services:
  app:
    image: ansible-role-pm2-app-test
    environment: &environment
      - STAGE=testing
    build:
      args:
        stage: test
